// Comprehensive timezone list for dropdown
export const timezones = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  { value: 'America/New_York', label: 'America/New_York (Eastern Time)' },
  { value: 'America/Chicago', label: 'America/Chicago (Central Time)' },
  { value: 'America/Denver', label: 'America/Denver (Mountain Time)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (Pacific Time)' },
  { value: 'America/Anchorage', label: 'America/Anchorage (Alaska Time)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (Hawaii Time)' },
  { value: 'America/Toronto', label: 'America/Toronto (Eastern Time - Canada)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (Pacific Time - Canada)' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City (Central Time - Mexico)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (Brasilia Time)' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires (Argentina Time)' },
  { value: 'America/Lima', label: 'America/Lima (Peru Time)' },
  { value: 'America/Santiago', label: 'America/Santiago (Chile Time)' },
  { value: 'Europe/London', label: 'Europe/London (Greenwich Mean Time)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (Central European Time)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (Central European Time)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (Central European Time)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (Central European Time)' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam (Central European Time)' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm (Central European Time)' },
  { value: 'Europe/Oslo', label: 'Europe/Oslo (Central European Time)' },
  { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen (Central European Time)' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki (Eastern European Time)' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw (Central European Time)' },
  { value: 'Europe/Prague', label: 'Europe/Prague (Central European Time)' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna (Central European Time)' },
  { value: 'Europe/Zurich', label: 'Europe/Zurich (Central European Time)' },
  { value: 'Europe/Athens', label: 'Europe/Athens (Eastern European Time)' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul (Turkey Time)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (Moscow Time)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (Japan Standard Time)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (Korea Standard Time)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (China Standard Time)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (Hong Kong Time)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (Singapore Time)' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok (Indochina Time)' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta (Western Indonesia Time)' },
  { value: 'Asia/Manila', label: 'Asia/Manila (Philippine Time)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (India Standard Time)' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi (Pakistan Standard Time)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (Gulf Standard Time)' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran (Iran Standard Time)' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem (Israel Standard Time)' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh (Arabia Standard Time)' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (Eastern European Time)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (South Africa Standard Time)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (West Africa Time)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (East Africa Time)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (Australian Eastern Time)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (Australian Eastern Time)' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane (Australian Eastern Time)' },
  { value: 'Australia/Perth', label: 'Australia/Perth (Australian Western Time)' },
  { value: 'Australia/Adelaide', label: 'Australia/Adelaide (Australian Central Time)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (New Zealand Time)' },
  { value: 'Pacific/Fiji', label: 'Pacific/Fiji (Fiji Time)' },
  { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti (Tahiti Time)' },
  { value: 'Pacific/Guam', label: 'Pacific/Guam (Chamorro Time)' },
  { value: 'Pacific/Samoa', label: 'Pacific/Samoa (Samoa Time)' },
  { value: 'Atlantic/Azores', label: 'Atlantic/Azores (Azores Time)' },
  { value: 'Atlantic/Canary', label: 'Atlantic/Canary (Western European Time)' },
  { value: 'Atlantic/Cape_Verde', label: 'Atlantic/Cape_Verde (Cape Verde Time)' },
  { value: 'Indian/Maldives', label: 'Indian/Maldives (Maldives Time)' },
  { value: 'Indian/Mauritius', label: 'Indian/Mauritius (Mauritius Time)' },
  { value: 'Indian/Reunion', label: 'Indian/Reunion (Reunion Time)' },
  { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo (New Zealand Time)' },
  { value: 'Arctic/Longyearbyen', label: 'Arctic/Longyearbyen (Central European Time)' }
];
